-- 2026-08-27 · THE CLAIM STOPS BEING BLOCKED BY SOMEBODY ELSE'S ABANDONED PACK.
--
-- Context, and why this is not the fix people will think it is: 327 of 328 hint wallets are
-- keyed "dev:<deviceId>" because the RevenueCat app user id never reaches the page (kamo-app
-- 1.1.7 fixes that at the source; until it is deployed, hint_claim IS the delivery path for
-- every pack sold). See 2026-08-19-hint-device-claim.sql for the original four conditions.
--
-- ⚠️ WHAT THIS DOES NOT DO. Two people buying at the same moment remain unattributable — an
-- intent and a grant carry no shared key, so choosing between two overlapping purchases would
-- mean guessing with somebody's money. Those are still refused, both of them. This migration
-- does not raise the ceiling on TRUE concurrency and nothing here should be read as if it did.
--
-- WHAT IT DOES FIX is the collision that is not a collision. Condition 4 counted unclaimed
-- grants in "the last 20 minutes from now", so a grant from a device that bought and never came
-- back sat in that window and answered `ambiguous` to every other buyer for twenty minutes —
-- including buyers whose own purchase happened long after it. One abandoned pack blocked
-- everyone. The window is now anchored on THIS device's own intent instead of on the clock:
-- a grant that predates the intent cannot be this purchase and is no longer counted against it.
--
-- Safety argument, in one line: any device that could own the candidate grant must have stamped
-- an intent, and ANY other intent in the surrounding window still refuses — so the grants this
-- now allows through are exactly the ones no other device could have produced.

-- ── 1. hint_intents becomes an append-only log ──────────────────────────────────────────────
-- It was one row per device (`on conflict do update set created_at = now()`), which means a
-- device stamping a second time ERASED the evidence of its first — and that evidence is what
-- the ambiguity check below reads. With the old primary key, two buyers could be made to look
-- like one by the later of them simply tapping twice. The log keeps every stamp.
alter table public.hint_intents drop constraint if exists hint_intents_pkey;
alter table public.hint_intents add column if not exists id bigint generated by default as identity;
update public.hint_intents set id = default where id is null;
alter table public.hint_intents alter column id set not null;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'hint_intents_pkey') then
    alter table public.hint_intents add constraint hint_intents_pkey primary key (id);
  end if;
end $$;
create index if not exists hint_intents_dev_time on public.hint_intents (dev_key, created_at desc);
create index if not exists hint_intents_time on public.hint_intents (created_at);
create index if not exists hint_grants_unclaimed_time on public.hint_grants (created_at) where claimed_by is null;

-- ── 2. the stamp: plain insert, no more overwrite ───────────────────────────────────────────
-- Signature unchanged on purpose. index.html deploys on push and this database does not, so
-- during any deploy both are live and a page loaded a minute ago still calls this exact shape.
create or replace function public.hint_intent(p_dev text)
returns json language plpgsql security definer set search_path to 'public' as $$
begin
  if p_dev is null or p_dev not like 'dev:%' then
    return json_build_object('ok', false, 'reason', 'bad_input');
  end if;
  insert into public.hint_intents (dev_key) values (p_dev);
  return json_build_object('ok', true);
end;
$$;

-- ── 3. the claim, anchored on the intent ────────────────────────────────────────────────────
-- Every refusal the original had is still here. The only behaviour that changes is WHICH grants
-- count as competition: they are now measured against this device's own intent instead of
-- against the wall clock.
create or replace function public.hint_claim(p_dev text)
returns json language plpgsql security definer set search_path to 'public' as $$
declare
  v_intent_at timestamptz;
  v_grant     public.hint_grants;
  v_bal       integer;
  -- How long a purchase may plausibly take from the tap that stamps the intent to the webhook
  -- landing: Apple's sheet, Face ID, an SCA step, two servers. 15 minutes is generous by an
  -- order of magnitude, and generous is the safe direction — it widens what counts as
  -- COMPETITION, never what counts as a match.
  v_span      interval := interval '15 minutes';
begin
  if p_dev is null or p_dev not like 'dev:%' then
    return json_build_object('claimed', false, 'reason', 'bad_input');
  end if;

  -- (1) once, ever — unchanged, and checked first so a repeat caller gets its balance back
  -- rather than a refusal it cannot act on.
  if exists (select 1 from public.hint_grants where claimed_by = p_dev) then
    return json_build_object('claimed', false, 'reason', 'already_claimed',
      'balance', coalesce((select balance from public.hint_wallet where owner = p_dev), 0));
  end if;

  -- (2) this device opened Apple's sheet recently — unchanged, but the timestamp is now kept:
  -- it is the anchor everything below is measured from.
  select max(created_at) into v_intent_at
    from public.hint_intents
   where dev_key = p_dev and created_at > now() - interval '20 minutes';
  if v_intent_at is null then
    return json_build_object('claimed', false, 'reason', 'no_intent');
  end if;

  -- (3) the candidate: the FIRST unclaimed grant to land after this device stamped. A grant
  -- older than the intent cannot be this purchase — that is the whole change.
  select * into v_grant from public.hint_grants
   where claimed_by is null
     and owner <> p_dev and owner not like 'dev:%'
     and created_at > v_intent_at
     and created_at <= v_intent_at + v_span
   order by created_at
   for update skip locked
   limit 1;

  if v_grant.event_id is null then
    return json_build_object('claimed', false, 'reason', 'no_grant');
  end if;

  -- (4) NOBODY ELSE COULD HAVE PRODUCED IT. Any other device that bought in this neighbourhood
  -- stamped an intent, so one other intent anywhere between v_span before this one and the
  -- grant itself is enough to make the pairing a guess — and a guess here spends a stranger's
  -- money. Refuse both, as before.
  if exists (select 1 from public.hint_intents
              where dev_key <> p_dev
                and created_at >= v_intent_at - v_span
                and created_at <= v_grant.created_at) then
    return json_build_object('claimed', false, 'reason', 'ambiguous');
  end if;

  -- (5) and no second unclaimed grant sits in the same neighbourhood, which would mean two
  -- purchases landed and only one intent explains them — an unaccounted buyer.
  if exists (select 1 from public.hint_grants
              where claimed_by is null
                and event_id <> v_grant.event_id
                and owner not like 'dev:%'
                and created_at > v_intent_at
                and created_at <= v_grant.created_at + v_span) then
    return json_build_object('claimed', false, 'reason', 'ambiguous');
  end if;

  update public.hint_grants set claimed_by = p_dev where event_id = v_grant.event_id;

  insert into public.hint_wallet (owner, balance) values (p_dev, v_grant.units)
    on conflict (owner) do update
      set balance = public.hint_wallet.balance + excluded.balance, updated_at = now()
    returning balance into v_bal;

  return json_build_object('claimed', true, 'balance', v_bal);
end;
$$;

grant execute on function public.hint_intent(text) to anon, authenticated;
grant execute on function public.hint_claim(text)  to anon, authenticated;
